import type {
  Flashcard,
  Formula,
  PracticeQuestion,
  ProgressTracking,
  SearchResult,
  Source,
  Topic,
  Unit,
} from "@apmicro/shared-types";

const now = "2026-03-11T12:00:00.000Z";

export const sources: Source[] = [
  {
    id: "source-kacapyr",
    title: "AP Microeconomics Review Packet by Elia Kacapyr",
    shortTitle: "Kacapyr",
    author: "Elia Kacapyr",
    path: "C:\\Users\\timsc\\Downloads\\64-Elia Kacapyr.pdf",
    type: "packet",
    summary:
      "Review-oriented packet useful for concise AP phrasing, graph drill language, and last-minute refreshers.",
    tags: ["review", "graphs", "exam-language"],
    coverage: ["unit-1", "unit-2", "unit-3", "unit-4", "unit-5", "unit-6"],
    uploadedAt: now,
  },
  {
    id: "source-krugman",
    title: "Krugman's Economics for AP",
    shortTitle: "Krugman AP",
    author: "Paul Krugman and Robin Wells",
    path: "C:\\Users\\timsc\\Downloads\\krugman_s_economics_for_ap.pdf",
    type: "textbook",
    summary:
      "Full-length AP-aligned textbook with broader intuition, worked examples, and core graph explanations.",
    tags: ["textbook", "intuition", "worked-examples"],
    coverage: ["unit-1", "unit-2", "unit-3", "unit-4", "unit-5", "unit-6"],
    uploadedAt: now,
  },
  {
    id: "source-ced",
    title: "AP Microeconomics Course and Exam Description",
    shortTitle: "College Board CED",
    author: "College Board",
    path: "C:\\Users\\timsc\\Downloads\\ap-microeconomics-course-and-exam-description.pdf",
    type: "course-guide",
    summary:
      "Primary source for unit structure, official skill categories, and AP-style language.",
    tags: ["official", "course-guide", "exam-scope"],
    coverage: ["unit-1", "unit-2", "unit-3", "unit-4", "unit-5", "unit-6"],
    uploadedAt: now,
  },
];

export const formulas: Formula[] = [
  {
    id: "formula-midpoint-elasticity",
    label: "Midpoint Elasticity",
    expression: "((Q2 - Q1) / ((Q2 + Q1)/2)) / ((P2 - P1) / ((P2 + P1)/2))",
    description: "Measures responsiveness using average price and quantity so direction does not matter.",
    variables: [
      { name: "Q1, Q2", meaning: "Original and new quantity" },
      { name: "P1, P2", meaning: "Original and new price" },
    ],
    apTip: "Take the absolute value for elasticity unless the question explicitly cares about sign.",
    topicIds: ["elasticity"],
  },
  {
    id: "formula-tax-revenue",
    label: "Tax Revenue",
    expression: "Tax per unit x Quantity sold after tax",
    description: "Rectangle between the buyer price and seller price at the after-tax quantity.",
    variables: [
      { name: "Tax per unit", meaning: "Vertical wedge created by the tax" },
      { name: "Quantity sold after tax", meaning: "New market quantity" },
    ],
    apTip: "Use the post-tax quantity, not the original equilibrium quantity.",
    topicIds: ["taxes-and-subsidies"],
  },
  {
    id: "formula-dwl",
    label: "Deadweight Loss",
    expression: "0.5 x base x height",
    description: "Triangle representing lost gains from trade after output moves away from the efficient quantity.",
    variables: [
      { name: "base", meaning: "Quantity reduction or increase away from efficiency" },
      { name: "height", meaning: "Wedge between marginal benefit and marginal cost" },
    ],
    apTip: "DWL comes from the trades that no longer happen, not the tax revenue rectangle.",
    topicIds: ["taxes-and-subsidies", "monopoly"],
  },
  {
    id: "formula-opportunity-cost",
    label: "Opportunity Cost on PPC",
    expression: "Units of Y forgone / Units of X gained",
    description: "Slope magnitude of the PPC when producing one more unit of a good.",
    variables: [
      { name: "Y forgone", meaning: "What you give up" },
      { name: "X gained", meaning: "What you get" },
    ],
    apTip: "Check which good is in the numerator. AP questions often flip the requested direction.",
    topicIds: ["ppc"],
  },
  {
    id: "formula-monopoly-profit",
    label: "Monopoly Profit",
    expression: "(Price - ATC) x Quantity",
    description: "Area of the profit rectangle where the monopolist produces at MR = MC and charges from demand.",
    variables: [
      { name: "Price", meaning: "Demand price at monopoly quantity" },
      { name: "ATC", meaning: "Average total cost at monopoly quantity" },
      { name: "Quantity", meaning: "Profit-maximizing output" },
    ],
    apTip: "The monopolist uses MR = MC to find quantity, then goes up to demand for price.",
    topicIds: ["monopoly"],
  },
];

export const topics: Topic[] = [
  {
    id: "ppc",
    slug: "ppc-and-opportunity-cost",
    unitId: "unit-1",
    title: "PPC and Opportunity Cost",
    shortDescription: "Use the production possibilities curve to map tradeoffs, efficiency, and comparative advantage.",
    tenSecondMeaning: "A PPC shows the max combinations an economy can produce and what it sacrifices when shifting output.",
    whyItMatters: "Unit 1 logic shows up again in trade, growth, and efficiency questions.",
    apTrap: "AP often asks for the opportunity cost in the reverse direction. Watch the numerator and denominator.",
    graphIds: ["ppc"],
    formulaIds: ["formula-opportunity-cost"],
    sourceIds: ["source-krugman", "source-ced", "source-kacapyr"],
    keyIdeas: ["attainable vs unattainable", "efficient vs inefficient", "increasing opportunity cost"],
    examPhrasing: ["calculate the opportunity cost", "identify a point that is productively efficient"],
    visualAnchors: ["bowed-out frontier", "outside point", "inside point"],
  },
  {
    id: "equilibrium",
    slug: "supply-and-demand-equilibrium",
    unitId: "unit-2",
    title: "Supply and Demand Equilibrium",
    shortDescription: "Find where supply and demand intersect and translate curve shifts into price and quantity changes.",
    tenSecondMeaning: "Equilibrium is the market-clearing point where quantity demanded equals quantity supplied.",
    whyItMatters: "This is the graph you build on for taxes, subsidies, ceilings, floors, and surplus.",
    apTrap: "A shift of a curve is different from movement along a curve. AP uses that distinction constantly.",
    graphIds: ["equilibrium"],
    formulaIds: [],
    sourceIds: ["source-krugman", "source-ced", "source-kacapyr"],
    keyIdeas: ["market-clearing price", "excess demand", "excess supply"],
    examPhrasing: ["identify the equilibrium quantity", "show the effect of an increase in demand"],
    visualAnchors: ["intersection point", "buyer curve", "seller curve"],
  },
  {
    id: "taxes-and-subsidies",
    slug: "taxes-and-subsidies",
    unitId: "unit-2",
    title: "Taxes and Subsidies",
    shortDescription: "Model wedges, government revenue or cost, and deadweight loss on a competitive market graph.",
    tenSecondMeaning: "Taxes push buyers and sellers apart; subsidies pull quantity past the efficient point.",
    whyItMatters: "Taxes and subsidies combine graph reading, area math, and policy reasoning in one place.",
    apTrap: "The tax burden is split by elasticity, not by who legally writes the check.",
    graphIds: ["tax", "subsidy"],
    formulaIds: ["formula-tax-revenue", "formula-dwl"],
    sourceIds: ["source-kacapyr", "source-ced", "source-krugman"],
    keyIdeas: ["tax wedge", "tax incidence", "deadweight loss", "subsidy cost"],
    examPhrasing: ["calculate tax revenue", "identify the change in consumer surplus"],
    visualAnchors: ["revenue rectangle", "dwl triangle", "new equilibrium quantity"],
  },
  {
    id: "monopoly",
    slug: "monopoly-profit-and-dwl",
    unitId: "unit-4",
    title: "Monopoly Profit and Deadweight Loss",
    shortDescription: "Use MR = MC for quantity, demand for price, and ATC for profit.",
    tenSecondMeaning: "Monopolists restrict output below the efficient level and charge a price above marginal cost.",
    whyItMatters: "This topic is one of the highest-payoff graph questions in Unit 4 FRQs.",
    apTrap: "Students often stop at MR = MC and forget to go up to the demand curve for the monopoly price.",
    graphIds: ["monopoly"],
    formulaIds: ["formula-monopoly-profit", "formula-dwl"],
    sourceIds: ["source-krugman", "source-kacapyr", "source-ced"],
    keyIdeas: ["profit rectangle", "consumer surplus reduction", "allocative inefficiency"],
    examPhrasing: ["identify the socially efficient output", "calculate the monopolist's profit"],
    visualAnchors: ["MR below demand", "profit rectangle", "DWL triangle"],
  },
  {
    id: "marginal-analysis",
    slug: "marginal-analysis-and-choice",
    unitId: "unit-1",
    title: "Marginal Analysis and Choice",
    shortDescription: "Make decisions by comparing marginal benefit and marginal cost.",
    tenSecondMeaning: "Do one more unit if the extra benefit is at least as large as the extra cost.",
    whyItMatters: "Marginal analysis is the logic behind demand curves, optimal hiring, and output choice.",
    apTrap: "Average values are not the decision rule. AP loves to test marginal thinking instead.",
    graphIds: [],
    formulaIds: [],
    sourceIds: ["source-ced", "source-krugman"],
    keyIdeas: ["marginal benefit", "marginal cost", "net benefit"],
    examPhrasing: ["determine the optimal level of output", "compare marginal benefit to marginal cost"],
    visualAnchors: ["extra unit", "incremental change"],
  },
];

export const units: Unit[] = [
  {
    id: "unit-1",
    number: 1,
    title: "Basic Economic Concepts",
    examWeight: "12-18%",
    description: "Scarcity, choice, opportunity cost, PPC, and comparative advantage foundations.",
    topicIds: ["scarcity-choice", "ppc", "comparative-advantage", "economic-systems", "marginal-analysis"],
  },
  {
    id: "unit-2",
    number: 2,
    title: "Supply and Demand",
    examWeight: "20-30%",
    description: "Demand, supply, equilibrium, elasticity, market interventions, and surplus.",
    topicIds: ["equilibrium", "demand-supply-shifts", "elasticity", "taxes-and-subsidies", "price-controls", "trade-policy"],
  },
  {
    id: "unit-3",
    number: 3,
    title: "Production, Cost, and Perfect Competition",
    examWeight: "22-25%",
    description: "Cost curves, marginal product, and competitive firm decision rules.",
    topicIds: ["production-functions", "cost-curves", "perfect-competition"],
  },
  {
    id: "unit-4",
    number: 4,
    title: "Imperfect Competition",
    examWeight: "15-22%",
    description: "Monopoly, oligopoly, and barriers to entry.",
    topicIds: ["monopoly", "monopolistic-competition-oligopoly"],
  },
  {
    id: "unit-5",
    number: 5,
    title: "Factor Markets",
    examWeight: "10-18%",
    description: "Labor demand, labor supply, MRP, MFC, and monopsony.",
    topicIds: ["factor-markets-labor", "factor-markets"],
  },
  {
    id: "unit-6",
    number: 6,
    title: "Market Failure and Government",
    examWeight: "12-18%",
    description: "Externalities, public goods, common resources, and inequality.",
    topicIds: ["externalities", "public-common-goods", "inequality", "market-failure"],
  },
];

export const flashcards: Flashcard[] = [
  {
    id: "fc-equilibrium",
    topicId: "equilibrium",
    front: "What does equilibrium mean on a supply and demand graph?",
    back: "Quantity demanded equals quantity supplied, so there is no tendency for price to change.",
    difficulty: "easy",
    tags: ["graph", "equilibrium"],
  },
  {
    id: "fc-tax-incidence",
    topicId: "taxes-and-subsidies",
    front: "Who bears more of a tax burden?",
    back: "The side of the market that is less elastic bears more of the burden.",
    difficulty: "medium",
    tags: ["tax", "elasticity"],
  },
  {
    id: "fc-monopoly-price",
    topicId: "monopoly",
    front: "How do you find monopoly price?",
    back: "Find the profit-maximizing quantity where MR = MC, then move up to the demand curve for price.",
    difficulty: "easy",
    tags: ["monopoly", "graph"],
  },
];

export const practiceQuestions: PracticeQuestion[] = [
  {
    id: "pq-equilibrium-shift",
    topicId: "equilibrium",
    unitId: "unit-2",
    type: "graph",
    origin: "ap-like",
    stem: "Demand increases while supply stays constant.",
    prompt: "Explain what happens to equilibrium price and quantity.",
    answer: "Both equilibrium price and equilibrium quantity increase.",
    explanation:
      "A rightward shift of demand moves the intersection with supply upward and to the right.",
    trap: "Do not call this a movement along demand. The demand curve itself shifted.",
    difficulty: "easy",
    sourceIds: ["source-ced", "source-krugman"],
    rubric: [],
  },
  {
    id: "pq-tax-dwl",
    topicId: "taxes-and-subsidies",
    unitId: "unit-2",
    type: "formula",
    origin: "ap-like",
    stem: "A per-unit tax raises the buyer price by $4, lowers the seller price by $2, and reduces quantity from 100 to 70.",
    prompt: "Find the tax revenue and deadweight loss.",
    answer: "Tax revenue = $420. Deadweight loss = $90.",
    explanation:
      "The per-unit tax wedge is $6. Revenue is 6 x 70. DWL is 0.5 x 30 x 6.",
    trap: "Use the after-tax quantity for revenue, not the original quantity.",
    difficulty: "medium",
    sourceIds: ["source-kacapyr"],
    rubric: [],
  },
  {
    id: "pq-monopoly-profit",
    topicId: "monopoly",
    unitId: "unit-4",
    type: "frq",
    origin: "ap-like",
    stem: "A monopolist produces where MR = MC at Q = 40. The demand curve shows P = 18 and ATC = 11 at that output.",
    prompt: "Calculate profit and identify whether output is allocatively efficient.",
    answer: "Profit is $280 and output is not allocatively efficient.",
    explanation:
      "Profit is (18 - 11) x 40. Monopoly output is below the socially efficient quantity because P exceeds MC.",
    trap: "Profit uses ATC, not MC.",
    difficulty: "hard",
    sourceIds: ["source-krugman", "source-ced"],
    rubric: ["profit is 280", "not allocatively efficient"],
  },
];

export const seededProgress: ProgressTracking[] = [
  {
    id: "progress-equilibrium",
    topicId: "equilibrium",
    confidence: 66,
    mastery: 58,
    lastStudiedAt: now,
    streakDays: 4,
    weakSpots: ["distinguishing shifts from movement along curves", "consumer surplus shading"],
    completedQuestionIds: ["pq-equilibrium-shift"],
  },
  {
    id: "progress-tax",
    topicId: "taxes-and-subsidies",
    confidence: 48,
    mastery: 44,
    lastStudiedAt: now,
    streakDays: 2,
    weakSpots: ["tax incidence", "dwl math"],
    completedQuestionIds: [],
  },
];

export const seededSearch: SearchResult[] = [
  {
    id: "search-equilibrium",
    kind: "topic",
    title: "Supply and Demand Equilibrium",
    summary: "Interactive graph, AP traps, and shift logic.",
    href: "/topic/supply-and-demand-equilibrium",
    sourceIds: ["source-ced", "source-krugman"],
  },
  {
    id: "search-tax-revenue",
    kind: "formula",
    title: "Tax Revenue",
    summary: "Use the tax wedge times the after-tax quantity.",
    href: "/graph-lab?module=tax-market",
    sourceIds: ["source-kacapyr"],
  },
  {
    id: "search-monopoly",
    kind: "graph",
    title: "Monopoly Profit and DWL",
    summary: "MR = MC for quantity, demand for price, ATC for profit.",
    href: "/graph-lab?module=monopoly-costs",
    sourceIds: ["source-krugman", "source-ced"],
  },
];
